import cart from "@/assets/cart.jpg"

export const categories = [
  "All Categories",
  "Electronics",
  "Fashion",
  "Home & Garden",
  "Vehicles",
  "Real Estate",
  "Jobs",
  "Services",
]

export const mockListings = [
  {
    id: "1",
    title: "Premium Wireless Headphones",
    price: 129,
    location: "New York, NY",
    image: cart,
    category: "Electronics",
    isNegotiable: true,
    isFeatured: true,
  },
  {
    id: "2",
    title: "Modern Office Chair",
    price: 250,
    location: "Los Angeles, CA",
    image: cart,
    category: "Home & Garden",
    isNegotiable: true,
    isFeatured: false,
  },
  {
    id: "3",
    title: "Smart Watch Series 8",
    price: 399,
    location: "Chicago, IL",
    image: cart,
    category: "Electronics",
    isNegotiable: false,
    isFeatured: true,
  },
  {
    id: "4",
    title: "Designer Leather Bag",
    price: 180,
    location: "Miami, FL",
    image: cart,
    category: "Fashion",
    isNegotiable: true,
    isFeatured: false,
  },
  {
    id: "5",
    title: "Gaming Console Pro",
    price: 499,
    location: "Seattle, WA",
    image: cart,
    category: "Electronics",
    isNegotiable: true,
    isFeatured: false,
  },
  {
    id: "6",
    title: "Vintage Coffee Table",
    price: 150,
    location: "Boston, MA",
    image: cart,
    category: "Home & Garden",
    isNegotiable: true,
    isFeatured: false,
  },
]
